### ISSUE TITLE
Install script not working at all now

### ISSUE THREAD

**Issue by landman16** [iNextrix/ASTPP#108]
Dear Support,

The install script for ASTPP v3.0 is not working on CentOS 7 anymore. Since it was updated a day ago. It will need checking again. As when i tried to reistall ASTPP the web gui has errors allot.

**Comment by landman16** [comment]
IS the install script going to be fixed?

**Comment by dev-astpp** [comment]
It may be the possible that it could be the kernel issue or some package missing issue that's why we have provide manual installation step you can verify. Because we also face that kind of situation.

https://astppdoc.atlassian.net/wiki/display/ASTPP/Install+ASTPP+3.0

Still if you are facing same issue then please share error log/screenshot

**Comment by gudge25** [comment]
Group development-tools does not exist.
./install.sh: line 323: update-rc.d: command not found
chown: invalid user: ‘freeswitch:daemon’
No package compat-libtermcap available.
No package libvpx2* available.
================================
my  errors  during installation 
================================

using 2 comands 
yum install bind-utils net-tools ntpdate ntp git cronie which libvpx-devel libvpx
yum groupinstall "Development tools" -y

solve issue for me
