### ISSUE TITLE
Fax T38 INCOMPATIBLE_DESTINATION duration no calculation 

### ISSUE THREAD

**Issue by tsv1991** [iNextrix/ASTPP#174]
If I send fax and after sending not answer then disposition = INCOMPATIBLE_DESTINATION and call not calculate.

**Comment by smrdoshi** [comment]
Of course it will not do billing calculation as call was not established
due to Incompatible destination.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.
