### ISSUE TITLE
DID Route Priority 

### ISSUE THREAD

**Issue by ChaudharyG** [iNextrix/ASTPP#210]
Hi Team, 

Hope you are doing well.. !!

We are trying to route DID on multiple gateways with priority. 

Exp.  123456789 --> GW1  --> First Priority 
          123456789 --> GW1  --> Second Priority 
          123456789 --> GW1  --> Third  Priority
our curent configureation is : 

DID = 123456789 
Call Type = OTHER
custom Dial plan is : sofia/gateway/TESTGW1/123456789,sofia/gateway/TESTGW2/123456789

According to above dial plan calls trying on both gateways at the same time.
So please guide us how setup sequential Dial. I mean the system will dial TESTGW1 gateway fist then try on other. 

Thanks

**Comment by arm123** [comment]
Hi,

That can be possible by implementing failover routing instead of multiple routing.
Please refer: https://wiki.freeswitch.org/wiki/Misc._Dialplan_Tools_bridge

According to that, your custom Dial string should be as below:
sofia/gateway/TESTGW1/123456789|sofia/gateway/TESTGW2/123456789

I hope it works.

Thanks,
Arpit
