### ISSUE TITLE
Generate invoice 

### ISSUE THREAD

**Issue by fikretkaplan001** [iNextrix/ASTPP#232]
If i create a invoice i get then next error
![test](https://user-images.githubusercontent.com/32026516/30517412-781e4168-9b5e-11e7-97fa-97f5b8d0ecb4.PNG)

also i get error on download of the created invoices like this
![test2](https://user-images.githubusercontent.com/32026516/30517415-86ec46f4-9b5e-11e7-8b20-7d66af783ce4.PNG)

**Comment by smrdoshi** [comment]
Run update.sh script to update source code and check it out. This issue is
resolved.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by fikretkaplan001** [comment]
i have updated and i get next error messages
![afbeelding](https://user-images.githubusercontent.com/32026516/31085778-5c12f022-a798-11e7-9791-2e5cba978376.png)

**Comment by fikretkaplan001** [comment]
I have found the problem but not yet a solution
i have changed default port of astpp from 8089 to 443 (https) also i have changed the base_url after this i can't download any invoices.

my astpp.conf of nginx 
----
        listen 443;
        listen [::]:443;
        server_name xxxxxxxx.com;

        ssl on;
        ssl_certificate /etc/letsencrypt/live/xxxxxxxx.com/cert.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxxxxxxx.com/privkey.pem;

....
....
-----

astpp-config.conf
---
base_url=https://xxxxxxx.com:443/

i have also tyr the base_url as next
base_url=https://xxxxxxx.com/

everything works good but invoice generation not.

Thanks

**Comment by smrdoshi** [comment]
Are you getting same error or any other?

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by TheDummyBjaze** [comment]
I am also getting same error, undefined variable : invoice_config_res 
 if i use ipaddress:8089 invoices are working but it is not working on domain http or https. 
Also when i change the index.php in /var/www/html/astpp/index.php line:22 
from production to development like define ( 'ENVIRONMENT', 'development' );
i am getting undefined variable error for invoices not the recipes on ipaddress:8089  so i guess there is a problem with invoice_download not the recipe download

**Comment by TheDummyBjaze** [comment]
Is there any update about this ?

**Comment by smrdoshi** [comment]
We have resolved that in last updates. 
Please re-open it if you still facing this problem.
