### ISSUE TITLE
Initial Increment Function on 6/6 Billing

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#289]
It seems our our number don't add correctly with a partner.

We are charging them on a 6/6 billing. In that case, if we put "6" in the initial increment field on the origination rate, is it redundant....? Or should we just leave it blank?

I guess I'm confused how it will change the billing calculations.

![image](https://user-images.githubusercontent.com/25807874/34328131-1190bbcc-e88b-11e7-89e2-52cfc4400e78.png)

**Comment by smrdoshi** [comment]
Yeah. If you want to set the billing 6/6 then its require to configure initial increment and increment to 6.

**Comment by slango-im** [comment]
Thank you, @smrdoshi. Does that mean then that the first 6 seconds of the call will be billed as well?

**Comment by devangn** [comment]
@slango-im 
As explained here, http://astpp.readthedocs.io/en/v3.5/Modules/Carriers/create_termination_rate.html
Initial Increment means, once call established caller will be charged at least that many seconds.
Increment means, after 'Initial Increment' the recursive block of fix number of seconds to charge.

It would be more preferable to use Google forum for such time of question so that all the other members also can help you directly.

**Comment by slango-im** [comment]
@devangn , thank you for the clarification. I will save such future questions for the Google forum
