### ISSUE TITLE
Unnecessary parameter in the reload_freeswitch() function?

### ISSUE THREAD

**Issue by tridcatij** [iNextrix/ASTPP#309]
Hey! Is the `$server_host` parameter obligatory for the [reload_freeswitch](https://github.com/iNextrix/ASTPP/blob/4185b6f00b2743b56243c145d3a8c5816bcb7183/web_interface/astpp/application/modules/freeswitch/models/freeswitch_model.php#L396-L408) function? I don't see any usage of it inside the function.
But, for example, you're passing it [here](https://github.com/iNextrix/ASTPP/blob/4185b6f00b2743b56243c145d3a8c5816bcb7183/web_interface/astpp/application/modules/freeswitch/controllers/freeswitch.php#L628)

P.S.
Little off-top - what is the **Channel** in the gateway's section for? In your manual there is no any description, and in the FS docs I didn't find anything although.

Thank you!

**Comment by smrdoshi** [comment]
That's true. No usage of $server_host parameter as we are fetching fs
servers information from the function itself.

Regarding Channel variable in gateway, initially, we had a plan to use that
as CC limit for gateway but then we moved it to trunk. Unfortunately forgot
to remove channel field from gateway module. So that the moment, that's not
in use.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
