### ISSUE TITLE
Please un-deprecate Apache

### ISSUE THREAD

**Issue by xrobau** [iNextrix/ASTPP#361]
Apache is just as fast as php-fpm, and is much more commonly used than nginx, especially on bigger, more commercial systems (eg, RHEL and CentOS).

In fact, some things are still hardcoded to use 'apache' as a username!

**Comment by powerpbx** [comment]
I would like to second this.  For a control panel, there are no benefits to using nginx imo.

**Comment by smrdoshi** [comment]
You can configure and run ASTPP on apache as well. By default, we are providing ASTPP to run on nginx.

**Comment by xrobau** [comment]
I think nginx is the wrong default. But that's, like, my opinion, man.

https://www.youtube.com/watch?v=pWdd6_ZxX8c

**Comment by AlexHeylin** [comment]
I've found no problems using nginx, the web server is something that's never caused me an issue.  We're seeing a lot of projects move to nginx. It can certainly perform under load, so that shouldn't be a concern. If you have other things on the server which require apache, I think you can install them both - just disable the default website in nginx.
