### ISSUE TITLE
ASTPP 3.6 failover gw rates

### ISSUE THREAD

**Issue by John91000** [iNextrix/ASTPP#523]
The problem is when the call goes to the failover gw, the price per minute is calculated as for the first gw
example gw1 to price 1 $
gw2 price 2$
if call going to gw2, the rate will 1$ , but need 2$

How can I fix it?  may need to install real time billing?

Thanks
Kind regard John K.
CallStru Group

**Comment by John91000** [comment]
i check live call show correct, if change gw, there show gw2
But in customer cdr show gw1. if call go gw2

**Comment by Hemdip** [comment]
@John91000 
Your problem will solve as per `Because that's how its designed. The gateway failover configuration under trunk is for one provider.
If you want failover through different provider's gateway, select multiple trunks under rate group.`

Furthermore I would request you to switch in V-4.0, It have lots of new features and enhancement [https://www.astppbilling.org/](url)

**Comment by John91000** [comment]
I did but anyway when call go to next gw failover, in cdrs show gw 1. but  call was in gw2. so rate same, but i want if it go next trunk, so rate too change.
